apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unity-webgl-k8s-cert
  namespace: unity-webgl-k8s
spec:
  secretName: unity-webgl-k8s-cert
  dnsNames:
    - unity-webgl-k8s.cseteram.dev
  renewBefore: 24h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer
